# Generated by Django 4.2.1 on 2023-05-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookname", models.CharField(max_length=40, null=True)),
                ("publisher", models.CharField(max_length=40, null=True)),
                ("price", models.IntegerField(null=True)),
                ("stock", models.IntegerField(null=True)),
            ],
        ),
    ]
