# Generated by Django 4.2.1 on 2023-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, null=True, verbose_name="이름")),
                ("address", models.CharField(max_length=50, null=True)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("email", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
